image: ficapy/docker:latest

variables:
  ALI_SERVER: "Host ali-server \n  User  root \n CheckHostIp no \n HostName xx.xx.xx.xx \n StrictHostKeyChecking no"

stages:
  - build
  - deploy

release:
  stage: deploy
  only:
    - master
  when: manual
  before_script:
    - eval $(ssh-agent -s)
    - echo "$ALI_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "$ALI_SERVER" > ~/.ssh/config'
  variables:
    SERVER: ali-server
  script:
    - rsync -r -avz --compress-level 9 --exclude={'__pycache__','allure-report','allure-results'} * $SERVER:/me/test-api --delete
    - ssh $SERVER "cd /me/test-api && UID=${UID} GID=${GID} docker-compose up -d --force-recreate"